create table coupon (
    coupon_id bigint generated by default as identity,
    max_count bigint,
    primary key (coupon_id)
);
create table coupon_issuance (
    coupon_id bigint,
    coupon_issuance_id bigint generated by default as identity,
    user_id varchar(255),
    primary key (coupon_issuance_id)
);

insert into coupon values(1, 100);